objects/Hotel__c.object
<CustomObject>
    <fields>
        <fullName>Address__c</fullName>
        <description>Address of the hotel</description>
        <inlineHelpText>Address of the hotel</inlineHelpText>
        <label>Address</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <description>City in which the hotel is located</description>
        <inlineHelpText>City in which the hotel is located</inlineHelpText>
        <label>City</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StarRating__c</fullName>
        <label>Star Rating</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Hotel</label>
    <nameField>
        <label>Hotel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hotels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Reservation__c.object
<CustomObject>
    <description>Room booking</description>
    <fields>
        <fullName>Email__c</fullName>
        <description>email used for reservation</description>
        <inlineHelpText>email used for reservation</inlineHelpText>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>EndDate__c</fullName>
        <description>end of reservation</description>
        <inlineHelpText>end of reservation</inlineHelpText>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Room__c</fullName>
        <description>Room being booked</description>
        <inlineHelpText>Room being booked</inlineHelpText>
        <label>Room</label>
        <referenceTo>Room__c</referenceTo>
        <relationshipLabel>Reservations</relationshipLabel>
        <relationshipName>Reservations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <description>begining of reservation</description>
        <inlineHelpText>begining of reservation</inlineHelpText>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Reservation</label>
    <nameField>
        <label>Reservation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reservations</pluralLabel>
    <recordTypes>
        <fullName>Reservation</fullName>
        <active>true</active>
        <description>Confirmed reservation</description>
        <label>Reservation</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Room__c.object
<CustomObject>
    <description>A Room in a hotel</description>
    <fields>
        <fullName>AirConditioner__c</fullName>
        <defaultValue>false</defaultValue>
        <description>presence of air conditioning in the room</description>
        <inlineHelpText>presence of air conditioning in the room</inlineHelpText>
        <label>Air Conditioner</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Guests__c</fullName>
        <description>Number of guests the room can fit</description>
        <inlineHelpText>Number of guests the room can fit</inlineHelpText>
        <label>Guests</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Hotel__c</fullName>
        <description>The hotel in which the room is located</description>
        <inlineHelpText>The hotel in which the room is located</inlineHelpText>
        <label>Hotel</label>
        <referenceTo>Hotel__c</referenceTo>
        <relationshipLabel>Rooms</relationshipLabel>
        <relationshipName>Rooms</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>MiniBar__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Presence of mini bar in the room</description>
        <inlineHelpText>Presence of mini bar in the room</inlineHelpText>
        <label>Mini Bar</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NightlyRate__c</fullName>
        <description>Rent cost per night</description>
        <inlineHelpText>Rent cost per night</inlineHelpText>
        <label>Nightly Rate</label>
        <precision>12</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>NoSmoking__c</fullName>
        <defaultValue>false</defaultValue>
        <description>The room is completely smoke-free</description>
        <inlineHelpText>The room is completely smoke-free</inlineHelpText>
        <label>No Smoking</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <description>Quantity of rooms of that type in the hotel</description>
        <inlineHelpText>Quantity of rooms of that type in the hotel</inlineHelpText>
        <label>Quantity</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RoomService__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Presence room service (e.g. food delivery to the door) in the room</description>
        <inlineHelpText>Presence room service (e.g. food delivery to the door) in the room</inlineHelpText>
        <label>Room Service</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>WiFi__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Presence of Wi-Fi in the room</description>
        <inlineHelpText>Presence of Wi-Fi in the room</inlineHelpText>
        <label>Wi-Fi</label>
        <type>Checkbox</type>
    </fields>
    <label>Room</label>
    <nameField>
        <label>Room Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rooms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/RoomBookingMainCmpControllerTest.cls
@isTest
public class RoomBookingMainCmpControllerTest {
    @isTest static void testRoomBookingMainCmpController() {
        
        //create hotel(s)
        Hotel__c Hotel = new Hotel__c();
        Hotel.Name = 'Hotel';
        Hotel.City__c ='Minsk';
        Hotel.Address__c = 'qwerty';
        Hotel.StarRating__c = '5';
        insert Hotel;
        
        //create room(s)
        Room__c Room1 = new Room__c();
        Room1.Hotel__c = Hotel.Id;
        Room1.Name = 'qwertty';
        Room1.Guests__c = 1;
        Room1.NightlyRate__c = 99;
        Room1.AirConditioner__c = True;
        Room1.RoomService__c = True;
        Room1.NoSmoking__c = True;
        Room1.WiFi__c = True;
        Room1.MiniBar__c = True;
        Room1.Quantity__c = 5;
        insert Room1;
        
        //create reservation(s) 
        Reservation__c Reservation1 = new Reservation__c();
        Reservation1.Name ='qwerty';
        Reservation1.Room__c =Room1.Id;
        Reservation1.StartDate__c = date.parse('05/01/2025');
        Reservation1.EndDate__c = date.parse('05/30/2025');
        Reservation1.Email__c = 'qwerty@azerty.com';
        Reservation1.RecordTypeId = '0122w000000Y1TyAAK';
        insert Reservation1;
        
        Reservation__c Reservation2 = new Reservation__c();
        Reservation2.Name ='qwerty';
        Reservation2.Room__c =Room1.Id;
        Reservation2.StartDate__c = date.parse('04/01/2025');
        Reservation2.EndDate__c = date.parse('04/30/2025');
        Reservation2.Email__c = 'qwerty@azerty.com';
        Reservation2.RecordTypeId = '0122w000000Y1TyAAK';
        insert Reservation2;
        
        Reservation__c Reservation3 = new Reservation__c();
        Reservation3.Name ='qwerty';
        Reservation3.Room__c =Room1.Id;
        Reservation3.StartDate__c = date.parse('06/01/2025');
        Reservation3.EndDate__c = date.parse('06/30/2025');
        Reservation3.Email__c = 'qwerty@azerty.com';
        Reservation3.RecordTypeId = '0122w000000Y1TyAAK';
        insert Reservation3;
        
        Reservation__c Reservation4 = new Reservation__c();
        Reservation4.Name ='qwerty';
        Reservation4.Room__c =Room1.Id;
        Reservation4.StartDate__c = date.parse('04/15/2025');
        Reservation4.EndDate__c = date.parse('05/15/2025');
        Reservation4.Email__c = 'qwerty@azerty.com';
        Reservation4.RecordTypeId = '0122w000000Y1TyAAK';
        insert Reservation4;
        
        Reservation__c Reservation5 = new Reservation__c();
        Reservation5.Name ='qwerty';
        Reservation5.Room__c =Room1.Id;
        Reservation5.StartDate__c = date.parse('05/15/2025');
        Reservation5.EndDate__c = date.parse('06/15/2025');
        Reservation5.Email__c = 'qwerty@azerty.com';
        Reservation5.RecordTypeId = '0122w000000Y1TyAAK';
        insert Reservation5;
        
        List<Hotel__c> HotelList1 = RoomBookingMainCmpController.getHotels('Minsk', 1, 0, 300, date.parse('05/01/2025'), date.parse('05/30/2025'), True, True, True, True, True); 
        
        //check for general correctness
        System.assertEquals(HotelList1.size(), 1);
        System.assertEquals(HotelList1[0].Rooms__r[0].Quantity__c, 2);
        
        //minPrice>maxPrice
        List<Hotel__c> HotelList4 = RoomBookingMainCmpController.getHotels('Minsk', 1, 300, 100, date.parse('05/01/2025'), date.parse('05/30/2025'), True, True, True, True, True); 
        System.assertEquals(HotelList4.size(), 0);
        
        //minPrice<0
        List<Hotel__c> HotelList5 = RoomBookingMainCmpController.getHotels('Minsk', 1, -100, 100, date.parse('05/01/2025'), date.parse('05/30/2025'), True, True, True, True, True); 
        System.assertEquals(HotelList5.size(), 0);
        
        //checkIn>checkOut
        List<Hotel__c> HotelList6 = RoomBookingMainCmpController.getHotels('Minsk', 1, 0, 100, date.parse('05/30/2025'), date.parse('05/01/2025'), True, True, True, True, True); 
        System.assertEquals(HotelList6.size(), 0);
        
        //checkIn<today
        List<Hotel__c> HotelList7 = RoomBookingMainCmpController.getHotels('Minsk', 1, 0, 100, system.today()-1, date.parse('05/01/2030'), True, True, True, True, True); 
        System.assertEquals(HotelList7.size(), 0);
        
    }
}