objects/Hotel__c.object
<CustomObject>
    <fields>
        <fullName>Address__c</fullName>
        <description>Address of the hotel</description>
        <inlineHelpText>Address of the hotel</inlineHelpText>
        <label>Address</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <description>City in which the hotel is located</description>
        <inlineHelpText>City in which the hotel is located</inlineHelpText>
        <label>City</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StarRating__c</fullName>
        <label>Star Rating</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Hotel</label>
    <nameField>
        <label>Hotel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hotels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Room__c.object
<CustomObject>
    <description>A Room in a hotel</description>
    <fields>
        <fullName>AirConditioner__c</fullName>
        <defaultValue>false</defaultValue>
        <description>presence of air conditioning in the room</description>
        <inlineHelpText>presence of air conditioning in the room</inlineHelpText>
        <label>Air Conditioner</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Guests__c</fullName>
        <description>Number of guests the room can fit</description>
        <inlineHelpText>Number of guests the room can fit</inlineHelpText>
        <label>Guests</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Hotel__c</fullName>
        <description>The hotel in which the room is located</description>
        <inlineHelpText>The hotel in which the room is located</inlineHelpText>
        <label>Hotel</label>
        <referenceTo>Hotel__c</referenceTo>
        <relationshipLabel>Rooms</relationshipLabel>
        <relationshipName>Rooms</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>MiniBar__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Presence of mini bar in the room</description>
        <inlineHelpText>Presence of mini bar in the room</inlineHelpText>
        <label>Mini Bar</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NightlyRate__c</fullName>
        <description>Rent cost per night</description>
        <inlineHelpText>Rent cost per night</inlineHelpText>
        <label>Nightly Rate</label>
        <precision>12</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>NoSmoking__c</fullName>
        <defaultValue>false</defaultValue>
        <description>The room is completely smoke-free</description>
        <inlineHelpText>The room is completely smoke-free</inlineHelpText>
        <label>No Smoking</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <description>Quantity of rooms of that type in the hotel</description>
        <inlineHelpText>Quantity of rooms of that type in the hotel</inlineHelpText>
        <label>Quantity</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RoomService__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Presence room service (e.g. food delivery to the door) in the room</description>
        <inlineHelpText>Presence room service (e.g. food delivery to the door) in the room</inlineHelpText>
        <label>Room Service</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>WiFi__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Presence of Wi-Fi in the room</description>
        <inlineHelpText>Presence of Wi-Fi in the room</inlineHelpText>
        <label>Wi-Fi</label>
        <type>Checkbox</type>
    </fields>
    <label>Room</label>
    <nameField>
        <label>Room Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rooms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ReservationModalCmpControllerTest.cls
@isTest
public class ReservationModalCmpControllerTest {
    @isTest static void testReservationModalCmpController() {
        
        //create hotel(s)
        Hotel__c Hotel = new Hotel__c();
        Hotel.Name = 'Hotel';
        Hotel.City__c ='Minsk';
        Hotel.Address__c = 'qwerty';
        Hotel.StarRating__c = '5';
        insert Hotel;
        
        //create room(s)
        Room__c Room1 = new Room__c();
        Room1.Hotel__c = Hotel.Id;
        Room1.Name = 'qwertty';
        Room1.Guests__c = 1;
        Room1.NightlyRate__c = 99;
        Room1.AirConditioner__c = True;
        Room1.RoomService__c = True;
        Room1.NoSmoking__c = True;
        Room1.WiFi__c = True;
        Room1.MiniBar__c = True;
        Room1.Quantity__c = 5;
        insert Room1;
        
        Boolean result1 = ReservationModalCmpController.makeReservation('qwerty', 'qwerty@azerty.com', date.parse('05/01/2025'), date.parse('05/30/2025'), Room1.Id);
        
        System.assertEquals(result1, true);
    }
}