objects/Hotel__c.object
<CustomObject>
    <fields>
        <fullName>Address__c</fullName>
        <description>Address of the hotel</description>
        <inlineHelpText>Address of the hotel</inlineHelpText>
        <label>Address</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <description>City in which the hotel is located</description>
        <inlineHelpText>City in which the hotel is located</inlineHelpText>
        <label>City</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StarRating__c</fullName>
        <label>Star Rating</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Hotel</label>
    <nameField>
        <label>Hotel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hotels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Reservation__c.object
<CustomObject>
    <description>Room booking</description>
    <fields>
        <fullName>EndDate__c</fullName>
        <description>end of reservation</description>
        <inlineHelpText>end of reservation</inlineHelpText>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Room__c</fullName>
        <description>Room being booked</description>
        <inlineHelpText>Room being booked</inlineHelpText>
        <label>Room</label>
        <referenceTo>Room__c</referenceTo>
        <relationshipLabel>Reservations</relationshipLabel>
        <relationshipName>Reservations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <description>begining of reservation</description>
        <inlineHelpText>begining of reservation</inlineHelpText>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Reservation</label>
    <nameField>
        <label>Reservation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reservations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Room__c.object
<CustomObject>
    <description>A Room in a hotel</description>
    <fields>
        <fullName>AirConditioner__c</fullName>
        <defaultValue>false</defaultValue>
        <description>presence of air conditioning in the room</description>
        <inlineHelpText>presence of air conditioning in the room</inlineHelpText>
        <label>Air Conditioner</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Guests__c</fullName>
        <description>Number of guests the room can fit</description>
        <inlineHelpText>Number of guests the room can fit</inlineHelpText>
        <label>Guests</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Hotel__c</fullName>
        <description>The hotel in which the room is located</description>
        <inlineHelpText>The hotel in which the room is located</inlineHelpText>
        <label>Hotel</label>
        <referenceTo>Hotel__c</referenceTo>
        <relationshipLabel>Rooms</relationshipLabel>
        <relationshipName>Rooms</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Image__c</fullName>
        <description>room photo (1280x720 fit best)</description>
        <inlineHelpText>room photo (1280x720 fit best)</inlineHelpText>
        <label>Image</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>MiniBar__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Presence of mini bar in the room</description>
        <inlineHelpText>Presence of mini bar in the room</inlineHelpText>
        <label>Mini Bar</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NightlyRate__c</fullName>
        <description>Rent cost per night</description>
        <inlineHelpText>Rent cost per night</inlineHelpText>
        <label>Nightly Rate</label>
        <precision>12</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>NoSmoking__c</fullName>
        <defaultValue>false</defaultValue>
        <description>The room is completely smoke-free</description>
        <inlineHelpText>The room is completely smoke-free</inlineHelpText>
        <label>No Smoking</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <description>Quantity of rooms of that type in the hotel</description>
        <inlineHelpText>Quantity of rooms of that type in the hotel</inlineHelpText>
        <label>Quantity</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RoomService__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Presence room service (e.g. food delivery to the door) in the room</description>
        <inlineHelpText>Presence room service (e.g. food delivery to the door) in the room</inlineHelpText>
        <label>Room Service</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>WiFi__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Presence of Wi-Fi in the room</description>
        <inlineHelpText>Presence of Wi-Fi in the room</inlineHelpText>
        <label>Wi-Fi</label>
        <type>Checkbox</type>
    </fields>
    <label>Room</label>
    <nameField>
        <label>Room Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rooms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/RoomBookingMainCmpController.cls
public class RoomBookingMainCmpController {
    
    //get list of hotels and rooms
    @AuraEnabled public static List<Hotel__c> getHotels(String city, Integer guests, Integer minPrice, Integer maxPrice, Date checkInDate, Date checkOutDate, Boolean wiFi, Boolean miniBar, Boolean airConditioner, Boolean roomService, Boolean noSmoking) {
        
        List<Hotel__c> HotelList = new List<Hotel__c>();
        
        //abort method if some of the inputs are critically imvalid
        if(minPrice<0 || minPrice > maxPrice || checkInDate > checkOutDate || checkInDate < system.today()) {
            return HotelList;
        }
        
        //start soql query
        String SoqlQuery = ' SELECT Name,City__c,Address__c,StarRating__c, (SELECT Name, Guests__c, NightlyRate__c, WiFi__c, RoomService__c, MiniBar__c, NoSmoking__c, AirConditioner__c, Hotel__c, Image__c, Quantity__c FROM Rooms__r WHERE ';
        
        //add guests condition to query
        SoqlQuery += ' Guests__c >= :guests ';
        if (maxPrice != null || minPrice != null || wiFi == true || miniBar == true  || airConditioner == true || noSmoking == true || roomService == true) {
            SoqlQuery += ' AND ';
        }
        
        //add minimal price condition to query 
        if (minPrice != null) {
            SoqlQuery += ' NightlyRate__c >= :minPrice ';
            //add 'AND'
            if (maxPrice != null || wiFi == true || miniBar == true  || airConditioner == true || noSmoking == true || roomService == true) {
                SoqlQuery += ' AND ';
            }
        }
        
        //add maximal price condition to query 
        if (maxPrice != null) {
            SoqlQuery += ' NightlyRate__c <= :maxPrice ';
            //add 'AND'
            if (wiFi == true || miniBar == true  || airConditioner == true || noSmoking == true || roomService == true) {
                SoqlQuery += ' AND ';
            }
        }
        
        //add Wi-Fi condition to query 
        if (wiFi == true) {
            SoqlQuery += ' WiFi__c = true ';
            //add 'AND'
            if (miniBar == true  || airConditioner == true || noSmoking == true || roomService == true) {
                SoqlQuery += ' AND ';
            }
        }
        
        //add minibar condition to query 
        if (miniBar == true) {
            SoqlQuery += ' MiniBar__c = true ';
            //add 'AND'
            if (airConditioner == true || noSmoking == true || roomService == true) {
                SoqlQuery += ' AND ';
            }
        }
        
        //add air conditioner condition to query 
        if (airConditioner == true) {
            SoqlQuery += ' AirConditioner__c = true ';
            //add 'AND'
            if (noSmoking == true || roomService == true) {
                SoqlQuery += ' AND ';
            }
        }
        
        //add no smoking condition to query 
        if (noSmoking == true) {
            SoqlQuery += ' NoSmoking__c = true ';
            //add 'AND'
            if (roomService == true) {
                SoqlQuery += ' AND ';
            }
        }
        
        //add room service condition to query 
        if (roomService == true) {
            SoqlQuery += ' RoomService__c = true ';
        }
        
        //finish query
        SoqlQuery +=  ' ORDER BY NightlyRate__c DESC) FROM Hotel__c WHERE City__c = :city';
        
        HotelList = database.query(soqlQuery);    
        
        //get a list of room id's to query reservations all at once
        List<String> IdList = new List<String>();
        
        for(Hotel__c Hotel: HotelList){ 
            for(Room__c Room : Hotel.Rooms__r) {
                IdList.add(Room.Id);
            }
        }
        
        //get a list of reservations overlapping with selected time period for all queried rooms
        List<Reservation__c>  ReservationList = [SELECT StartDate__c, EndDate__c, Room__c FROM Reservation__c WHERE Room__c IN :IdList AND(NOT((EndDate__c < :checkInDate AND StartDate__c < :checkInDate) OR (StartDate__c > :checkOutDate AND EndDate__c > :checkOutDate))) AND RecordTypeId = '0122w000000Y1TyAAK'];

        //check if there are free rooms of that type left 
        for(Hotel__c Hotel: HotelList){ 
            
            for(Room__c Room : Hotel.Rooms__r) {
                
                //check every day of searched time range to find the day with highest amount of reservations for the room type
                if (ReservationList.size() > 0) {
                    Integer MaxReservationQuantity = 0;
                    for (Date dt = checkInDate; dt.daysBetween(checkOutDate) > 0; dt = dt.addDays(1)) {
                        Integer CurrentDayReservationQuantity = 0;
                        for (Reservation__c res : ReservationList) {
                            if (res.Room__c == Room.Id &&(res.EndDate__c.daysBetween(dt) <= 0 || res.StartDate__c.daysBetween(dt) >= 0)) {
                                CurrentDayReservationQuantity++;
                            }
                        }
                        if (CurrentDayReservationQuantity > MaxReservationQuantity) {
                            MaxReservationQuantity = CurrentDayReservationQuantity;
                        }
                    }
                    //final returned quantity of returned room type equals (full Quantity - max(fitting reservations)) 
                    Room.Quantity__c -= MaxReservationQuantity;
                }
            }
        }
        return HotelList;
    }
}