objects/Hotel__c.object
<CustomObject>
    <fields>
        <fullName>Address__c</fullName>
        <description>Address of the hotel</description>
        <inlineHelpText>Address of the hotel</inlineHelpText>
        <label>Address</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Hotel</label>
    <nameField>
        <label>Hotel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hotels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Reservation__c.object
<CustomObject>
    <description>Room booking</description>
    <fields>
        <fullName>Email__c</fullName>
        <description>email used for reservation</description>
        <inlineHelpText>email used for reservation</inlineHelpText>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>EndDate__c</fullName>
        <description>end of reservation</description>
        <inlineHelpText>end of reservation</inlineHelpText>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Room__c</fullName>
        <description>Room being booked</description>
        <inlineHelpText>Room being booked</inlineHelpText>
        <label>Room</label>
        <referenceTo>Room__c</referenceTo>
        <relationshipLabel>Reservations</relationshipLabel>
        <relationshipName>Reservations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <description>begining of reservation</description>
        <inlineHelpText>begining of reservation</inlineHelpText>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Reservation</label>
    <nameField>
        <label>Reservation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reservations</pluralLabel>
    <recordTypes>
        <fullName>Reservation</fullName>
        <active>true</active>
        <description>Confirmed reservation</description>
        <label>Reservation</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Room__c.object
<CustomObject>
    <description>A Room in a hotel</description>
    <fields>
        <fullName>Guests__c</fullName>
        <description>Number of guests the room can fit</description>
        <inlineHelpText>Number of guests the room can fit</inlineHelpText>
        <label>Guests</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Hotel__c</fullName>
        <description>The hotel in which the room is located</description>
        <inlineHelpText>The hotel in which the room is located</inlineHelpText>
        <label>Hotel</label>
        <referenceTo>Hotel__c</referenceTo>
        <relationshipLabel>Rooms</relationshipLabel>
        <relationshipName>Rooms</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Room</label>
    <nameField>
        <label>Room Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rooms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ReservationModalCmpController.cls
public class ReservationModalCmpController {
    
    //create reservation based on stated data
    @AuraEnabled public static Boolean makeReservation(String name, String email, Date checkInDate, Date checkOutDate, String id) {
        
        //set reservation fields
        Reservation__c res = new Reservation__c();
        res.Room__c = id;
        res.StartDate__c = checkInDate;
        res.EndDate__c = checkOutDate;
        res.Email__c = email;
        Room__c Room = [SELECT Name, Guests__c, Hotel__r.Name FROM Room__c WHERE Id=:id LIMIT 1];
        res.Name= '' + name + ' ' + Room.Name + ' for ' + Room.Guests__c + ' ' + ' in ' + Room.Hotel__r.Name + ' ' + checkInDate.format() + ' - ' + checkOutDate.format();
        res.RecordTypeId = '0122w000000XzWOAA0';
        
        //try to insert reservation
        Database.SaveResult result = Database.insert(res, false);
        
        //if reservation is was inserted successfully, send confirmation email
        if(result.isSuccess() == true) {
            ReservationModalCmpController.sendConfirmationEmail(email, name, checkInDate, checkOutDate, id);
        }
        
        //return results of insertion attempt
        return result.isSuccess();
    }
    
    //send confirmation email after reservation is created succesfully
    public static void sendConfirmationEmail (String EmailAddress, String Name, Date checkInDate, Date checkOutDate, String RoomId) {
        
        Messaging.reserveSingleEmailCapacity(1);
        
        Messaging.SingleEmailMessage Mail = new Messaging.SingleEmailMessage();
        
        String[] toAddresses = new String[] {EmailAddress}; 
            String[] ccAddresses = new String[] {EmailAddress};
                
                mail.setToAddresses(toAddresses);
        mail.setCcAddresses(ccAddresses);
        
        mail.setReplyTo('support@bookaroom.com');
        
        mail.setSenderDisplayName('Bookaroom Support');
        
        mail.setSubject('Reservation confirmation letter');
        
        mail.setBccSender(false);
        
        mail.setUseSignature(false);
        
        Room__c Room = [SELECT Name, Guests__c, Hotel__r.Name, Hotel__r.Address__c FROM Room__c WHERE Id = :RoomId];
        
        mail.setHtmlBody('<p><strong>' +Name + '</strong>, Your reservation was registered successfully!</p>'
                         +'<p>Hotel: ' + Room.Hotel__r.Name + ', ' + Room.Hotel__r.Address__c + '</p>'
                         +'<p>Room: ' + Room.Name + ' for ' + Room.Guests__c + '</p>'
                         +'<p>Check-in date: ' + checkInDate.format() + '</p>'
                         +'<p>Check-out date: ' + checkOutDate.format() + '</p>');
        
        Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
    }
}